displayName=Delayed Heals
author=DapperMickie
support=https://github.com/DapperMickie/delayed-healing
description=Shows when hunter meat and other delayed healing food will heal you
tags=delayed,healing,food,heal,heals,hunter,meat,hunter meat
plugins=com.github.dappermickie.delayed.healing.DelayedHealingPlugin
version=
build=standard
